### ISSUE TITLE
Do not tightly couple library with specific versions of font icons libraries

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron-react#91]
Right now there are a few places where we assume fontawesome@4, like the modal's close button for example. Components should allow for alternate nodes to be passed in.

Recently, on a project using this library which also was using fontawesome@5.8.1, I was forced to add hacky legacy overrides:

```css
/*
 * NOTE: This is a hack so we can use newer font awesome
 * icons than the one that cauldron is expecting
 */
.fa.fa-close::before {
  content: "\f00d"
}
```
